name: Tangle

on:
  push: {}
  workflow_dispatch: {}

jobs:
  tangle:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: gwennlbh/to-tangled@v0.4
        with:
          repo: rito.blue/rito
          ssh-key: ${{ secrets.TANGLED_KEY }}

